## Numpy: numerical Python

In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.23.5


In [5]:
m = np.array([1,2,3,4,5])
print(m)
print(m.ndim)    # to check dimension
print(type,(m))  # total no of elements
print(m.dtype)   

[1 2 3 4 5]
1
<class 'type'> [1 2 3 4 5]
int32


In [6]:
n = np.array([35,56,6.5,7.8])
print(n)
print(n.dtype)
nm = np.array([10,20,45.56,34.23])
print(nm)
print(nm.dtype)

[35.  56.   6.5  7.8]
float64
[10.   20.   45.56 34.23]
float64


In [7]:
ms = np.array([['gmit','abeyaantrix','ise','dsml']])
print(ms)
print(type(ms))
print(ms.dtype)
print(ms.shape)

ms = np.array(['gmit','abeyaantrix',20,35])
print(ms)
print(type(ms))
print(ms.dtype)
print(ms.shape)


[['gmit' 'abeyaantrix' 'ise' 'dsml']]
<class 'numpy.ndarray'>
<U11
(1, 4)
['gmit' 'abeyaantrix' '20' '35']
<class 'numpy.ndarray'>
<U11
(4,)


In [19]:
a = np.array([[1,2,3,4],[9,2,3,8],[1,1,1,2]])
print(a.shape)

(3, 4)


## Array creation with builtin methods

In [8]:
#zeros

z1 = np.zeros(5) # creats a 10 array with 5 elements set to zero
z2 = np.zeros((3,4))  # creats a 2d array with 3*4 shape and elements set to garbage 
print(z1)
print()
print(z2)


[0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
#one

o1 = np.ones(5) # creats a 10 array with 5 elements set to ones
o2 = np.ones((3,4))  # creats a 2d array with 3*4 shape and elements set to garbage 
print(o1)
print()
print(o2)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
#empty

e1 = np.empty(5) # creats a 10 array with 5 elements set to garbage
e2 = np.empty((3,4))  # creats a 2d array with 3*4 shape and elements set to garbage 
print(e1)
print()
print(e2)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Numpy linearly spaced arrays

In [33]:
b = np.array(5)

# start,stop : step
# end = stop - step
# default start is 0
# default stop is length os array
# default step is 1

print(b)
print(type(b))
print(b.ndim)

c = np.arange(5)
print(c)

5
<class 'numpy.ndarray'>
0
[0 1 2 3 4]


In [95]:
b1 = np.arange(10,15)
print(b1)

b2 = np.arange(1,10,2)
print(b2)

b3 = np.arange(1,6)[::-1]
print(b3)

b4 = np.arange(10,60,10)
print(b4)

b5 = np.arange(-6,0)[::-1]
print(b5)

b6 = np.arange(-1,-6,-1)
print(b6)

b7 = np.arange(0,0.5,6)
print(b7)

[10 11 12 13 14]
[1 3 5 7 9]
[5 4 3 2 1]
[10 20 30 40 50]
[-1 -2 -3 -4 -5 -6]
[-1 -2 -3 -4 -5]
[0.]


## Linspace

In [61]:
c = np.linspace(1,5,3)
print(c)

c1 = np.linspace(10,500,5)
print(c1)

c2 = np.linspace(1,5,5)
print(c2)

# when you know the step size use arange
# when you need specific no of element within specified range use linspace

[1. 3. 5.]
[ 10.  132.5 255.  377.5 500. ]
[1. 2. 3. 4. 5.]


## Random function to genrate random number

In [67]:
# uniformly distrubuted random numbers

r = np.random.rand(4)  # between 0 t0 1 and only pass the array size
print(r)

d = np.random.rand(3,4)
print('d=\n',d)

[0.63735653 0.51439238 0.35973029 0.70160513]
d=
 [[0.13386656 0.85260467 0.92429373 0.37850621]
 [0.37486145 0.71295461 0.20393046 0.35674902]
 [0.68650024 0.31067499 0.74982701 0.48556519]]


In [69]:
# integer random numbers

r1 = np.random.randint(1,10,3)  #lowlimit, uplimit, and shape of array 
# between 1 to 10 gen 5 random numbers

print(r1)

r2 = np.random.randint(1,50,(3,4))
print('r2\n',r2)

[2 9 4]
r2
 [[12 35 38 10]
 [39 11 19 14]
 [40  3  3 42]]


In [70]:
# full function 

f = np.full((3,4),100)
print(f)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [73]:
# seed for controlling random number genration

np.random.seed(23)  # to control randomness or to generate same random number
r3 = np.random.randint(1,50,(3,2))
print('r3\n',r3)

r3
 [[20 39]
 [41 10]
 [41 32]]


## Array Reshape

In [74]:
np.random.seed(23)
ar = np.random.randint(1,50,(2,6))
print(ar)
print(ar.shape)

[[20 39 41 10 41 32]
 [46 13 28 40 27 26]]
(2, 6)


In [84]:
ar1 = ar.reshape(3,4) # while reshaping the value must equals to 12 (3,4) (2,6) bcoz org ar is in (2,6)
print(ar1)
print(ar1.shape)
print(ar1.ndim)  # dimension is 2d
print('\n')

ar2 = ar.reshape(2,6)
print(ar2)
print('\n')

ar3 = ar.reshape(12,1)
print(ar3)

[[20 39 41 10]
 [41 32 46 13]
 [28 40 27 26]]
(3, 4)
2


[[20 39 41 10 41 32]
 [46 13 28 40 27 26]]


[[20]
 [39]
 [41]
 [10]
 [41]
 [32]
 [46]
 [13]
 [28]
 [40]
 [27]
 [26]]


In [85]:
# conver 1d to 2d

g = np.arange(1,11)
print(g.ndim)
print(g.shape)

1
(10,)


In [88]:
g1 = g.reshape(5,2)
print(g1.shape)
print(g1.ndim)

(5, 2)
2


In [90]:
h = np.arange(1,26).reshape(5,5)
h

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [98]:
g2 = np.arange(1,50,2)
g2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [99]:
g2 = g2.reshape(5,5)
g2

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

## Accessing techniques

In [100]:
np.random.seed(0)
i = np.random.randint(1,500,(5,5))
i

array([[173,  48, 118, 193, 324],
       [252, 196, 360,  10, 212],
       [278, 243, 293,  88,  71],
       [473,  89, 397, 315, 194],
       [487,  40,  88, 175,  89]])

In [103]:
# row index, column index
print(i[0,0])
print(i[2,3])
print('\n')

#row index
print(i[3])
print(i[0])

173
88


[473  89 397 315 194]
[173  48 118 193 324]
