# Neural Network

### input layer: 
   - it accecpt the user input along with initial weight in the model
   - inputs will be multiplied by weights summed together and passed to the next layer
    
### hidden layer:
   - it is the complex structure cabable to complex hidden pattern inside the data
   - no specific rule to select it
   - half of the size of input neural size

### output layer:
   - here we get the final output process based on the input process of previous layer

### activation function: 
   - it is resposible for introducing non lenearity forr the model without activation neural network become linear model
   - mathematically activation function decide wether a neuron wil be active or not by calculating the weighted sum and adding bias to it
   

## Steps

- input passes from input layer via activation reaches hidden layer and then finally output layer with learnt output (based on initial weight of model)
- compute error between model predicted value as actual value
- Backward propagation: using the error computed backward propagate the error so as to updated the weights of model
- process of forward and bakward propagation is called one iteration
- Iteration: one time forward and backward propagation of single sample in the data
- Epoch: one time forward and backward propagation of entire data is called one Epoch
- Batch size: no of samples in each iteration
- ReLu will be most preferred in hiddden layer

## Libraries used in Deep learning
- Tensorflow: a library for building Neural Network by Google
- Keras: it is high level Neural Network library built on top of Tensorflow
- PyTorch: a library for building neural network
- Theno outdated

In [7]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [10]:
import keras
from keras.models import Sequential  # we will build sequential architecture
from keras.layers import Dense       # for adding the layers to sequential model

In [11]:
import numpy as np
Ain  = np.array([1,2,3,4,5,6])
Bout = np.array([4,5,6,7,8,9])
print(Ain)
print(Bout)

[1 2 3 4 5 6]
[4 5 6 7 8 9]


In [12]:
Reg_model = Sequential()
Reg_model.add(Dense( units = 1, input_shape = [1]))
Reg_model.compile(optimizer = 'sgd', loss = 'mean_squared_error' )

In [13]:
Reg_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2 (8.00 Byte)
Trainable params: 2 (8.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [26]:
Reg_model.fit(Ain, Bout, epochs=500)

# try for 1 epoch, check result
# try for 10 epoch. check result
# 100 check result
# 500 check result

Epoch 1/500
1/1 [==============================] - 0s 14ms/step - loss: 0.0162
Epoch 2/500
1/1 [==============================] - 0s 14ms/step - loss: 0.0161
Epoch 3/500
1/1 [==============================] - 0s 13ms/step - loss: 0.0160
Epoch 4/500
1/1 [==============================] - 0s 13ms/step - loss: 0.0158
Epoch 5/500
1/1 [==============================] - 0s 13ms/step - loss: 0.0157
Epoch 6/500
1/1 [==============================] - 0s 15ms/step - loss: 0.0156
Epoch 7/500
1/1 [==============================] - 0s 13ms/step - loss: 0.0155
Epoch 8/500
1/1 [==============================] - 0s 12ms/step - loss: 0.0154
Epoch 9/500
1/1 [==============================] - 0s 15ms/step - loss: 0.0153
Epoch 10/500
1/1 [==============================] - 0s 13ms/step - loss: 0.0152
Epoch 11/500
1/1 [==============================] - 0s 15ms/step - loss: 0.0151
Epoch 12/500
1/1 [==============================] - 0s 13ms/step - loss: 0.0149
Epoch 13/500
1/1 [==============================]

1/1 [==============================] - 0s 11ms/step - loss: 0.0037
Epoch 205/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0036
Epoch 206/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0036
Epoch 207/500
1/1 [==============================] - 0s 12ms/step - loss: 0.0036
Epoch 208/500
1/1 [==============================] - 0s 12ms/step - loss: 0.0036
Epoch 209/500
1/1 [==============================] - 0s 12ms/step - loss: 0.0035
Epoch 210/500
1/1 [==============================] - 0s 12ms/step - loss: 0.0035
Epoch 211/500
1/1 [==============================] - 0s 12ms/step - loss: 0.0035
Epoch 212/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0035
Epoch 213/500
1/1 [==============================] - 0s 10ms/step - loss: 0.0034
Epoch 214/500
1/1 [==============================] - 0s 12ms/step - loss: 0.0034
Epoch 215/500
1/1 [==============================] - 0s 9ms/step - loss: 0.0034
Epoch 216/500
1/1 [========================

1/1 [==============================] - 0s 12ms/step - loss: 8.4422e-04
Epoch 406/500
1/1 [==============================] - 0s 11ms/step - loss: 8.3806e-04
Epoch 407/500
1/1 [==============================] - 0s 13ms/step - loss: 8.3196e-04
Epoch 408/500
1/1 [==============================] - 0s 9ms/step - loss: 8.2590e-04
Epoch 409/500
1/1 [==============================] - 0s 9ms/step - loss: 8.1988e-04
Epoch 410/500
1/1 [==============================] - 0s 11ms/step - loss: 8.1391e-04
Epoch 411/500
1/1 [==============================] - 0s 12ms/step - loss: 8.0798e-04
Epoch 412/500
1/1 [==============================] - 0s 11ms/step - loss: 8.0210e-04
Epoch 413/500
1/1 [==============================] - 0s 13ms/step - loss: 7.9625e-04
Epoch 414/500
1/1 [==============================] - 0s 13ms/step - loss: 7.9045e-04
Epoch 415/500
1/1 [==============================] - 0s 11ms/step - loss: 7.8469e-04
Epoch 416/500
1/1 [==============================] - 0s 12ms/step - loss: 7.7897e

In [24]:
Reg_model.weights

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.0677656]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([2.7098818], dtype=float32)>]

In [25]:
Reg_model.predict(np.array([1]))

1/1 [==============================] - 0s 39ms/step


array([[3.7776475]], dtype=float32)